spring:
  profiles:
    active: dev
  #jsp
  mvc:
    view: 
      prefix: /WEB-INF/views/
      suffix: .jsp

  #jdbc 설정
  datasource:
    url: jdbc:mysql://localhost:3306/ohouse?autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: koreait2020
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  #파일업로드 설정
  servlet:
    multipart:
      location: C:/Temp      file-size-threshold: 1MB
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.ohouse.model 
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:logback-${spring.profiles.active}.xml

# Tomcat port change
server:
  port: 8090
  
# java -jar -Dspring.profiles.active=prod 커맨드창에 입력하면 prod.xml로 바꿔줌