spring:
  #jsp
  mvc:
    view: 
      prefix: /WEB-INF/views/
      suffix: .jsp
  #jdbc 설정
  datasource:
    url: jdbc:mysql://localhost:3306/ohouse?autoReconnect=true
    username: root
    password: koreait2020
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.ohouse.model 
  configuration:
    map-underscore-to-camel-case: true

# Tomcat port change
server:
  port: 8090